### ISSUE TITLE
Tracking site-packages in the venv

### ISSUE THREAD

**Issue by godwnwaswa** [oogunjob/FX-Signal-Copier-Telegram-Bot#1]
I realized after putting the Fx-signal copier files in the root of my venv and hitting 'git add . ' all the files under Lib are tracked too. they seem to be a lot, is it a must i track them too for the app to function properly on heroku?

**Comment by oogunjob** [comment]
Not entirely sure if I understand the context of this issue, but I do have a demonstration video showcasing step by step the installation from GitHub to deploy onto Heroku along with the steps in README. Here is a link to the video, let me know if this able to help you.
https://www.youtube.com/watch?v=QTCco30M3BY&t=5s

**Comment by oogunjob** [comment]
Closing this issue with reference to the YouTube video for proper set up
